apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-storage
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "biz-db-chart.labels" . | indent 4 }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.backup }}
