apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "biz-db-chart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount.redis }}
  selector:
    matchLabels:
      app: redis
  serviceName: redis-svc
  template:
    metadata:
      labels:
        app: redis
{{ include "biz-db-chart.labels" . | indent 8 }}
    spec:
      containers:
      - name: redis
        image: {{ .Values.image.redis }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.resources.redis.requests.cpu }}
            memory: {{ .Values.resources.redis.requests.memory }}
          limits:
            cpu: {{ .Values.resources.redis.limits.cpu }}
            memory: {{ .Values.resources.redis.limits.memory }}
        command:
        - redis-server
        - --requirepass
        - $(REDIS_PASSWORD)
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-redis-secret
              key: redis-auth
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      storageClassName: {{ .Values.storageClass }}
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage.redis }}
