apiVersion: v1
kind: Secret
metadata:
  name: db-redis-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "biz-db-chart.labels" . | indent 4 }}
type: Opaque
data:
  mysql-root-pwd: {{ .Values.auth.mysqlRootPassword | b64enc }}
  redis-auth: {{ .Values.auth.redisPassword | b64enc }}
