apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: blog
  labels:
    app: mysql-exporter
spec:
  selector:
    app: mysql-exporter
  ports:
  - name: metrics
    port: 9104
    targetPort: 9104

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
      - name: exporter
        image: m.daocloud.io/docker.io/prom/mysqld-exporter:v0.14.0
        env:
        - name: DATA_SOURCE_NAME
          #value: "exporter:Exporter123!@tcp(mysql-exporter.blog.svc.cluster.local:3306)/"
          value: "exporter:Exporter123!@tcp(mysql.blog.svc.cluster.local:3306)/"
          #value: "exporter:Exporter123!@tcp(10.107.112.51:3306)/"
          #value: "exporter:Exporter123!@tcp(10.111.94.131:3306)/"
        ports:
        - containerPort: 9104

