apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-storage
  namespace: biz
spec:
  storageClassName: local-path
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
